[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "http://micuentacuentos.com/*"
  to = "https://www.micuentacuentos.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.micuentacuentos.com/*"
  to = "https://www.micuentacuentos.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://micuentacuentos.com/*"
  to = "https://www.micuentacuentos.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  for = "/*"
    [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' https: data: blob:; connect-src 'self' https: wss:;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Upgrade-Insecure-Requests = "1"
    X-Forwarded-Proto = "https"